### ISSUE TITLE
ps-dispatch doesn't have those files anymore.

### ISSUE THREAD

**Issue by KemuriHunter** [ImMacky/mk-atmRobbery#3]
ps-dispatch doesn't have those files anymore i'm a little lost where you put the lines of code.

**Comment by JTRIP05** [comment]
Correct... ps-dispatch has been updated, could we get an update on where to put the code? Thank you!

**Comment by BionicWRLD** [comment]
We all want to use this code but you need to update it for PS-Dispatch new update @ImMacky

**Comment by Th3shitshows** [comment]
any update on this yet?

**Comment by Italusx** [comment]
Probably not .. theres no mini game (hack) that shows up after you install it. even after putting codes in proper directories.    Author hasn't replied.   simple fix = remove resource find another lol

**Comment by ImMacky** [comment]
Hey so sorry for the delay of this fix.

I've been diving into this the past four hours and I'm still very confused. I'm still working on the fix.

**Comment by ImMacky** [comment]
Hey this is fixed with release [**1.2.1**](https://github.com/ImMacky/mk-atmRobbery/releases/tag/1.2.1) I still am having issues with `ps-dispatch` I added the functionality which can be changed in `cl_client.lua` but for now you can use the default `qb-policejob` alert system or implement your own in the `Dispatch()` function.

I'm going to begin work on `2.0` just need to find some inspiration and some new ideas!
